### index page, not logged in
GET http://localhost:3000/

### index page, logged in as jackyneo123 with an expired token
GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzA2OWMxMDUzMWY2YWZjMzcwMzRjYiIsImZpcnN0X25hbWUiOiJKYWNrIiwibGFzdF9uYW1lIjoiTmVvIiwidXNlcm5hbWUiOiJqYWNreW5lbzEyMyIsInBhc3N3b3JkIjoiJDJhJDEwJFdyVThGajVYYWZSVC9KdFg1bTlTMHVyQ0cvYldwQ2hoQkljNk1mRXd2MEpDT3hnLlNSRG15IiwibWVtYmVyX3N0YXR1cyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjg1OTc2NjcxLCJleHAiOjE2ODU5NzY3MzF9.i8rEPVyaJHnOffRjdUZJaoEIYmiuXsfrAbFACMlH-k8

### index page, logged in as jackyneo123
GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzA2OWMxMDUzMWY2YWZjMzcwMzRjYiIsImZpcnN0X25hbWUiOiJKYWNrIiwibGFzdF9uYW1lIjoiTmVvIiwidXNlcm5hbWUiOiJqYWNreW5lbzEyMyIsInBhc3N3b3JkIjoiJDJhJDEwJFdyVThGajVYYWZSVC9KdFg1bTlTMHVyQ0cvYldwQ2hoQkljNk1mRXd2MEpDT3hnLlNSRG15IiwibWVtYmVyX3N0YXR1cyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjg1OTQ4MjgyfQ.a9kAYaMew76gqbtCukeq2b_mrkRT6CNE4eAPKIRfUoQ

### log in page
GET http://localhost:3000/auth/login

### log in as jackyneo123
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "jackyneo123",
    "password": "password123",
    "confirmpassword": "password123"
}

### log in as johnnyboi
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "johnnyboi",
    "password": "password123",
    "confirmpassword": "password123"
}

### sign up page
GET http://localhost:3000/auth/signup

### log out  as jackyneo123
GET http://localhost:3000/auth/loggingout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzA2OWMxMDUzMWY2YWZjMzcwMzRjYiIsImZpcnN0X25hbWUiOiJKYWNrIiwibGFzdF9uYW1lIjoiTmVvIiwidXNlcm5hbWUiOiJqYWNreW5lbzEyMyIsInBhc3N3b3JkIjoiJDJhJDEwJFdyVThGajVYYWZSVC9KdFg1bTlTMHVyQ0cvYldwQ2hoQkljNk1mRXd2MEpDT3hnLlNSRG15IiwibWVtYmVyX3N0YXR1cyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjg1OTQ4MjgyfQ.a9kAYaMew76gqbtCukeq2b_mrkRT6CNE4eAPKIRfUoQ


### GET jackyneo123 profile as a non-user
GET http://localhost:3000/users/647069c10531f6afc37034cb

### GET johnnyboi profile as a non-user
GET http://localhost:3000/users/6475c1ecad833067e6c44f3c

### GET jackyneo123 member status page as no one
GET http://localhost:3000/users/647069c10531f6afc37034cb/memberstatus

### GET jackyneo123 member status page as jackyneo123
GET http://localhost:3000/users/647069c10531f6afc37034cb/memberstatus
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzA2OWMxMDUzMWY2YWZjMzcwMzRjYiIsImZpcnN0X25hbWUiOiJKYWNrIiwibGFzdF9uYW1lIjoiTmVvIiwidXNlcm5hbWUiOiJqYWNreW5lbzEyMyIsInBhc3N3b3JkIjoiJDJhJDEwJFdyVThGajVYYWZSVC9KdFg1bTlTMHVyQ0cvYldwQ2hoQkljNk1mRXd2MEpDT3hnLlNSRG15IiwibWVtYmVyX3N0YXR1cyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjg1OTQ4MjgyfQ.a9kAYaMew76gqbtCukeq2b_mrkRT6CNE4eAPKIRfUoQ

### GET jackyneo123 member status page as johnnyboi
GET http://localhost:3000/users/647069c10531f6afc37034cb/memberstatus
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzVjMWVjYWQ4MzMwNjdlNmM0NGYzYyIsImZpcnN0X25hbWUiOiJqb2huIiwibGFzdF9uYW1lIjoid2ljayIsInVzZXJuYW1lIjoiam9obm55Ym9pIiwicGFzc3dvcmQiOiIkMmEkMTAkT0Q1OS5rUFVkRlRQbXkvUFYvSDJyZVZVNWlpR1NQRDkxaGF3aTI5amdkN2ExM2dpYXEwcTIiLCJtZW1iZXJfc3RhdHVzIjoiQmFzaWMiLCJfX3YiOjB9LCJpYXQiOjE2ODU5NTU3NTR9.PDHSJAkrWsp5kNHQMlkEcv8gmD9Fd6UYKYj-ee72-GU

### POST johnnyboi member status page as johnnyboi, with wrong passcode
POST http://localhost:3000/users/6475c1ecad833067e6c44f3c/memberstatus
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzVjMWVjYWQ4MzMwNjdlNmM0NGYzYyIsImZpcnN0X25hbWUiOiJqb2huIiwibGFzdF9uYW1lIjoid2ljayIsInVzZXJuYW1lIjoiam9obm55Ym9pIiwicGFzc3dvcmQiOiIkMmEkMTAkT0Q1OS5rUFVkRlRQbXkvUFYvSDJyZVZVNWlpR1NQRDkxaGF3aTI5amdkN2ExM2dpYXEwcTIiLCJtZW1iZXJfc3RhdHVzIjoiQmFzaWMiLCJfX3YiOjB9LCJpYXQiOjE2ODU5NTU3NTR9.PDHSJAkrWsp5kNHQMlkEcv8gmD9Fd6UYKYj-ee72-GU
Content-Type: application/json

{
    "member_password": "blabla"
}

### POST johnnyboi member status page as johnnyboi, with correct premium passcode
POST http://localhost:3000/users/6475c1ecad833067e6c44f3c/memberstatus
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzVjMWVjYWQ4MzMwNjdlNmM0NGYzYyIsImZpcnN0X25hbWUiOiJqb2huIiwibGFzdF9uYW1lIjoid2ljayIsInVzZXJuYW1lIjoiam9obm55Ym9pIiwicGFzc3dvcmQiOiIkMmEkMTAkT0Q1OS5rUFVkRlRQbXkvUFYvSDJyZVZVNWlpR1NQRDkxaGF3aTI5amdkN2ExM2dpYXEwcTIiLCJtZW1iZXJfc3RhdHVzIjoiQmFzaWMiLCJfX3YiOjB9LCJpYXQiOjE2ODU5NTU3NTR9.PDHSJAkrWsp5kNHQMlkEcv8gmD9Fd6UYKYj-ee72-GU
Content-Type: application/json

{
    "member_password": "ilikekittens"
}

### POST johnnyboi member status page as johnnyboi, with correct admin passcode
POST http://localhost:3000/users/6475c1ecad833067e6c44f3c/memberstatus
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzVjMWVjYWQ4MzMwNjdlNmM0NGYzYyIsImZpcnN0X25hbWUiOiJqb2huIiwibGFzdF9uYW1lIjoid2ljayIsInVzZXJuYW1lIjoiam9obm55Ym9pIiwicGFzc3dvcmQiOiIkMmEkMTAkT0Q1OS5rUFVkRlRQbXkvUFYvSDJyZVZVNWlpR1NQRDkxaGF3aTI5amdkN2ExM2dpYXEwcTIiLCJtZW1iZXJfc3RhdHVzIjoiQmFzaWMiLCJfX3YiOjB9LCJpYXQiOjE2ODU5NTU3NTR9.PDHSJAkrWsp5kNHQMlkEcv8gmD9Fd6UYKYj-ee72-GU
Content-Type: application/json

{
    "member_password": "ialsolikepuppies"
}

### create a post as jackyneo123
GET http://localhost:3000/posts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzA2OWMxMDUzMWY2YWZjMzcwMzRjYiIsImZpcnN0X25hbWUiOiJKYWNrIiwibGFzdF9uYW1lIjoiTmVvIiwidXNlcm5hbWUiOiJqYWNreW5lbzEyMyIsInBhc3N3b3JkIjoiJDJhJDEwJFdyVThGajVYYWZSVC9KdFg1bTlTMHVyQ0cvYldwQ2hoQkljNk1mRXd2MEpDT3hnLlNSRG15IiwibWVtYmVyX3N0YXR1cyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjg1OTQ4MjgyfQ.a9kAYaMew76gqbtCukeq2b_mrkRT6CNE4eAPKIRfUoQ

### create a post as jackyneo123
POST http://localhost:3000/posts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzA2OWMxMDUzMWY2YWZjMzcwMzRjYiIsImZpcnN0X25hbWUiOiJKYWNrIiwibGFzdF9uYW1lIjoiTmVvIiwidXNlcm5hbWUiOiJqYWNreW5lbzEyMyIsInBhc3N3b3JkIjoiJDJhJDEwJFdyVThGajVYYWZSVC9KdFg1bTlTMHVyQ0cvYldwQ2hoQkljNk1mRXd2MEpDT3hnLlNSRG15IiwibWVtYmVyX3N0YXR1cyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjg1OTQ4MjgyfQ.a9kAYaMew76gqbtCukeq2b_mrkRT6CNE4eAPKIRfUoQ
Content-Type: application/json

{
    "title": "testing out a post creation by backend",
    "text": "this is suppose to be the text of the post. Is it readable in the DB?"
}

### delete a post as jackyneo123
DELETE http://localhost:3000/posts/647dac60e92ffb502b4119a6/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzA2OWMxMDUzMWY2YWZjMzcwMzRjYiIsImZpcnN0X25hbWUiOiJKYWNrIiwibGFzdF9uYW1lIjoiTmVvIiwidXNlcm5hbWUiOiJqYWNreW5lbzEyMyIsInBhc3N3b3JkIjoiJDJhJDEwJFdyVThGajVYYWZSVC9KdFg1bTlTMHVyQ0cvYldwQ2hoQkljNk1mRXd2MEpDT3hnLlNSRG15IiwibWVtYmVyX3N0YXR1cyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjg1OTQ4MjgyfQ.a9kAYaMew76gqbtCukeq2b_mrkRT6CNE4eAPKIRfUoQ

### get a post as not logged in
GET http://localhost:3000/posts/647dac60e92ffb502b4119a6

### get a post as jackyneo123
GET http://localhost:3000/posts/647dac60e92ffb502b4119a6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzA2OWMxMDUzMWY2YWZjMzcwMzRjYiIsImZpcnN0X25hbWUiOiJKYWNrIiwibGFzdF9uYW1lIjoiTmVvIiwidXNlcm5hbWUiOiJqYWNreW5lbzEyMyIsInBhc3N3b3JkIjoiJDJhJDEwJFdyVThGajVYYWZSVC9KdFg1bTlTMHVyQ0cvYldwQ2hoQkljNk1mRXd2MEpDT3hnLlNSRG15IiwibWVtYmVyX3N0YXR1cyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjg1OTQ4MjgyfQ.a9kAYaMew76gqbtCukeq2b_mrkRT6CNE4eAPKIRfUoQ

### posting a new comment as johnnyboi
POST http://localhost:3000/posts/647dac60e92ffb502b4119a6/comments/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzVjMWVjYWQ4MzMwNjdlNmM0NGYzYyIsImZpcnN0X25hbWUiOiJqb2huIiwibGFzdF9uYW1lIjoid2ljayIsInVzZXJuYW1lIjoiam9obm55Ym9pIiwicGFzc3dvcmQiOiIkMmEkMTAkT0Q1OS5rUFVkRlRQbXkvUFYvSDJyZVZVNWlpR1NQRDkxaGF3aTI5amdkN2ExM2dpYXEwcTIiLCJtZW1iZXJfc3RhdHVzIjoiQmFzaWMiLCJfX3YiOjB9LCJpYXQiOjE2ODU5NTU3NTR9.PDHSJAkrWsp5kNHQMlkEcv8gmD9Fd6UYKYj-ee72-GU
Content-Type: application/json

{
    "new_comment": "This is a comment made by johnnyboi. Is it captured?"
}

### replying to a comment as jackyneo123
POST http://localhost:3000/posts/647dac60e92ffb502b4119a6/comments/647daca8e92ffb502b4119b4/reply
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0NzA2OWMxMDUzMWY2YWZjMzcwMzRjYiIsImZpcnN0X25hbWUiOiJKYWNrIiwibGFzdF9uYW1lIjoiTmVvIiwidXNlcm5hbWUiOiJqYWNreW5lbzEyMyIsInBhc3N3b3JkIjoiJDJhJDEwJFdyVThGajVYYWZSVC9KdFg1bTlTMHVyQ0cvYldwQ2hoQkljNk1mRXd2MEpDT3hnLlNSRG15IiwibWVtYmVyX3N0YXR1cyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjg1OTQ4MjgyfQ.a9kAYaMew76gqbtCukeq2b_mrkRT6CNE4eAPKIRfUoQ
Content-Type: application/json

{
    "new_reply": "This is a reply made by jacky to johnny's comment."
}
